HPM/Controllers/UserProjectsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HPM.Services;
using HPM.Models.ViewModels;
using Microsoft.AspNet.Identity;


namespace HPM.Controllers
{
    public class UserProjectsController : Controller
    {
        private readonly UserProjectService _service;

        // GET: UserProjects
        public ActionResult Index()
        {
            return View();
        }

        public UserProjectsController()
        {
            _service = new UserProjectService();
        }

        [HttpPost]
        public ActionResult LoadUserProjects()
        {
            var list = _service.LoadUserProject();
            return PartialView("~/Views/UserProjects/_LoadUserProjects.cshtml", list);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public JsonResult Save(UserProjectModel models)
        {
            var userId = User.Identity.GetUserId();
            var isSave = _service.SaveUserProject(models, userId);
            return Json(isSave);
        }

        [HttpPost]
        public JsonResult Delete(decimal? id)
        {
            var isDeleted = _service.DeleteUserProject(id);
            return Json(isDeleted);
        }

    }
}

HPM/Views/UserProjects/Create.cshtml
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section scripts{
<script src="~/Js/UserProject/create.js"></script>
    }
<div class="row animated fadeIn" ng-controller="createUserProjectCtrl">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <strong>User Projects</strong>
            </div>
            <form name="frm">
                <div class="card-block">
                    <div class="row m-1">
                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="Province"><strong>Projects</strong></label>
                                <ui-select ng-model="selUserProject.Project" theme="select2" title="Choose a type" on-select="loadProjects()"  name="projects" ng-required="true">
                                    <ui-select-match placeholder="Select a Name">{{$select.selected.Name}}</ui-select-match>
                                    <ui-select-choices repeat="item in projects | filter:  $select.search">
                                        <div ng-bind-html="item.Name"></div>
                                    </ui-select-choices>
                                </ui-select>
                                <span style="color:red" ng-show="(frm.projects.$touched || frm.projects.$dirty) && frm.projects.$invalid">
                                    <span ng-show="frm.projects.$error.required">
                                        Project is required.
                                    </span>
                                </span>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="Division"><strong>Users</strong></label>
                                <ui-select ng-model="selUserProject.User" theme="select2" title="Choose a type" on-select="loadUsers()" name="users" ng-required="true">
                                    <ui-select-match placeholder="Select a Name">{{$select.selected.Name}}</ui-select-match>
                                    <ui-select-choices repeat="item in users | filter:  $select.search">
                                        <div ng-bind-html="item.Name"></div>
                                    </ui-select-choices>
                                </ui-select>
                                <span style="color:red" ng-show="(frm.users.$touched || frm.users.$dirty) && frm.users.$invalid">
                                    <span ng-show="frm.users.$error.required">
                                        User is required.
                                    </span>
                                </span>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="Tehsil"><strong>Rights</strong></label>
                                <ui-select ng-model="selUserProject.Right" theme="select2" title="Choose a type" on-select="loadProjectRights()" name="rights" ng-required="true">
                                    <ui-select-match placeholder="Select a Name">{{$select.selected.Name}}</ui-select-match>
                                    <ui-select-choices repeat="item in projectRights | filter:  $select.search">
                                        <div ng-bind-html="item.Name"></div>
                                    </ui-select-choices>
                                </ui-select>
                                <span style="color:red" ng-show="(frm.rights.$touched || frm.rights.$dirty) && frm.rights.$invalid">
                                    <span ng-show="frm.rights.$error.required">
                                        Rights is required.
                                    </span>
                                </span>
                            </div>
                        </div>
                    </div>

                    <div class="row m-1">
                        <div class="col-md-12">
                            <button type="button" class="btn btn-sm btn-primary" ng-disabled="frm.$invalid" ng-click="save()"> <span class="fa fa-save"></span> Save</button>
                        </div>
                    </div>
                </div>
            </form>
           

        </div>
    </div>
</div>

HPM/Views/UserProjects/Index.cshtml
@{
    ViewBag.Title = "User Projects";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@section scripts{
 <script src="~/Js/UserProject/index.js"></script>
}

<div class="row animated fadeIn">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header card-header-primary text-white">
                <strong>User Projects</strong>
                <a title="Add new project" class="btn btn-sm btn-outline-primary float-right" style="color:white;" href="@Url.Action("Create","UserProjects")"><span class="fa fa-plus"></span></a>
            </div>
            <div class="card-block">
                <div id="divPartialView">

                </div>
            </div>

        </div>
    </div>
</div>

HPM/Views/UserProjects/_LoadUserProjects.cshtml
@model IEnumerable<HPM.Models.ViewModels.UserProjectModel>

<table class="table table-bordered table-striped table-hover" id="tblUserProject">
    <thead>
        <tr>
            <th>Sr #</th>
            <th>Project</th>
            <th>Project Url</th>
            <th>User</th>
            <th>Right</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>



        @foreach (var item in Model)
        {
            <tr>
                <td></td>
                <td>
                    @item.Project.Name
                </td>
                <td>
                    @item.Project.Url
                </td>
                <td>
                    @item.User.UserName
                </td>
                <td>
                    @item.Right.Name
                </td>
                <td>
                    <i onclick="deleteUserPro(@item.Id)" style="cursor:pointer;" class="fa fa-trash fa-2x"></i>
                </td>
            </tr>
        }
    </tbody>
</table>