HPM/Models/Designation.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HPM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Designation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Designation()
        {
            this.Developers = new HashSet<Developer>();
        }
    
        public decimal Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsEnable { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Developer> Developers { get; set; }
    }
}

HPM/Controllers/DesignationController.cs
using HPM.Models.ViewModels;
using HPM.Services;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HPM.Controllers
{
    public class DesignationController : Controller
    {
        private readonly DesignationService _service;


        public DesignationController()
        {
            _service = new DesignationService();
        }
        // GET: Designation
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult LoadDesignations()
        {
            var list = _service.LoadDesignations();
            return PartialView("~/Views/Designation/_LoadDesignation.cshtml", list);
        }

        [HttpPost]
        public ActionResult LoadDesignationDetail(decimal? id)
        {
            var developer = _service.LoadDesignationDetail(id);
            return Json(developer);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public JsonResult Save(DesignationModel models)
        {
            var userId = User.Identity.GetUserId();
            var isSave = _service.SaveDesignation(models, userId);
            return Json(isSave);
        }


        [HttpGet]
        public ActionResult Edit(string id)
        {
            ViewBag.Id = id;
            return View();
        }

        [HttpPost]
        public JsonResult Edit(DesignationModel models)
        {
            var userId = User.Identity.GetUserId();
            var isSave = _service.EditDesignation(models, userId);
            return Json(isSave);
        }



    }
}

HPM/Views/Designation/Create.cshtml
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section scripts{
    <script src="~/Js/Designation/create.js"></script>
}

<div class="row animated fadeIn" ng-controller="createDestCtrl">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header card-header-primary text-white">
                <strong>Create Designation</strong>
            </div>
            <div class="card-block">
                <form name="frm">

                    <div class="row m-1">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label><strong>Name</strong></label>
                                <input type="text" name="name" ng-model="dest.Name" class="form-control" required />
                                <span style="color:red;" ng-if="(frm.name.$touched || frm.name.$dirty ) && frm.name.$invalid">
                                    <span ng-show="frm.name.$error.required">Designation name is required. </span>
                                </span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label><strong>Description</strong></label>
                                <textarea class="form-control" ng-model="dest.Description"></textarea>
                            </div>
                        </div>

                    </div>


                    <div class="row m-1">
                        <div class="col-md-12">
                            <button type="button" class="btn btn-sm btn-primary" ng-disabled="frm.$invalid" ng-click="save()"> <span class="fa fa-save"></span> Save</button>
                        </div>
                    </div>
                </form>

            </div>

        </div>
    </div>
</div>

HPM/Views/Designation/Edit.cshtml
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section scripts{
    <script src="~/Js/Designation/edit.js"></script>
}

<div class="row animated fadeIn" ng-controller="editDestCtrl">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header card-header-primary text-white">
                <strong>Edit Designation</strong>
            </div>
            <div class="card-block">
                <form name="frm">

                    <div class="row m-1">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label><strong>Name</strong></label>
                                <input type="text" name="name" ng-model="dest.Name" class="form-control" required />
                                <span style="color:red;" ng-if="(frm.name.$touched || frm.name.$dirty ) && frm.name.$invalid">
                                    <span ng-show="frm.name.$error.required">Designation name is required. </span>
                                </span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label><strong>Description</strong></label>
                                <textarea class="form-control" ng-model="dest.Description"></textarea>
                            </div>
                        </div>

                    </div>


                    <div class="row m-1">
                        <div class="col-md-12">
                            <button type="button" class="btn btn-sm btn-primary" ng-disabled="frm.$invalid" ng-click="save()"> <span class="fa fa-save"></span> Save</button>
                        </div>
                    </div>
                </form>

            </div>

        </div>
    </div>
</div>


<input type="hidden" value="@ViewBag.Id" id="hidId" />

HPM/Views/Designation/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section scripts{
    <script src="~/Js/Designation/index.js"></script>
}

<div class="row animated fadeIn">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header card-header-primary text-white">
                <strong>Designations</strong>
                <a title="Add new Designation" class="btn btn-sm btn-outline-primary float-right" style="color:white;" href="@Url.Action("Create","Designation")"><span class="fa fa-plus"></span></a>
            </div>
            <div class="card-block">
                <div id="divPartialView">

                </div>
            </div>

        </div>
    </div>
</div>

HPM/Views/Designation/_LoadDesignation.cshtml
@model IEnumerable<HPM.Models.ViewModels.DesignationModel>

<table class="table table-hover table-striped table-bordered" id="tbl">
    <thead>
        <tr>
            <th>Sr #</th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td></td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    <a href="@Url.Action("Edit","Designation",new { id = item.Id})" target="_blank"><i style="cursor:pointer;" class="fa fa-edit fa-2x"></i> </a>
                </td>
            </tr>
        }
    </tbody>
</table>