HPM/Models/Program.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HPM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Program
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Program()
        {
            this.Projects = new HashSet<Project>();
        }
    
        public decimal Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsEnable { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Project> Projects { get; set; }
    }
}

HPM/Models/Project.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HPM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Project()
        {
            this.ProjectDevelopers = new HashSet<ProjectDeveloper>();
            this.UserProjectRights = new HashSet<UserProjectRight>();
            this.ProjectIterations = new HashSet<ProjectIteration>();
        }
    
        public decimal Id { get; set; }
        public string Name { get; set; }
        public string Url { get; set; }
        public string Image { get; set; }
        public string Description { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<int> ProjectOrder { get; set; }
        public Nullable<decimal> TechnologyId { get; set; }
        public Nullable<bool> IsEnable { get; set; }
        public string RequestType { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<decimal> ProgramId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectDeveloper> ProjectDevelopers { get; set; }
        public virtual Technology Technology { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserProjectRight> UserProjectRights { get; set; }
        public virtual Program Program { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectIteration> ProjectIterations { get; set; }
    }
}

HPM/Controllers/ProgramController.cs
using HPM.Models.ViewModels;
using HPM.Services;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HPM.Controllers
{
    public class ProgramController : Controller
    {
        private readonly ProgramService _service;

        public ProgramController()
        {
            _service = new ProgramService();
        }
        // GET: Program
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult LoadPrograms()
        {
            var list = _service.LoadPrograms();
            return PartialView("~/Views/Program/_LoadPrograms.cshtml", list);
        }

        [HttpPost]
        public ActionResult LoadProgramDetail(decimal? id)
        {
            var pro = _service.LoadProgramDetail(id);
            return Json(pro);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public JsonResult Save(ProgramModel model)
        {
            var userId = User.Identity.GetUserId();
            var isSave = _service.SaveProgram(model, userId);
            return Json(isSave);
        }


        [HttpGet]
        public ActionResult Edit(string id)
        {
            ViewBag.Id = id;
            return View();
        }

        [HttpPost]
        public JsonResult Edit(ProgramModel model)
        {
            var userId = User.Identity.GetUserId();
            var isSave = _service.EditProgram(model, userId);
            return Json(isSave);
        }

        [HttpPost]
        public ActionResult Disable(decimal? id)
        {
            var isDisable = _service.DisableProgram(id);
            return Json(isDisable);
        }

        //[HttpGet]
        //public ActionResult Projects()
        //{
        //    return View();
        //}

        //[HttpPost]
        //public ActionResult LoadProjects()
        //{
        //    var list = _service.LoadProjects();
        //    return PartialView("~/Views/Program/_LoadProjects.cshtml", list);
        //}

    }
}

HPM/Controllers/ProjectsController.cs
using HPM.Models.ViewModels;
using HPM.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Newtonsoft.Json;
using System.IO;

namespace HPM.Controllers
{
    public class ProjectsController : Controller
    {
        private readonly ProjectServices _services;
        public ProjectsController()
        {
            _services = new ProjectServices();
        }
        // GET: Projects
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult LoadProjects()
        {
            var list = _services.LoadProject();
            return PartialView("~/Views/Projects/_LoadProjects.cshtml", list);
        }

        [HttpPost]
        public ActionResult LoadProjectsDetail(decimal? id)
        {
            var pro = _services.LoadProjectDetail(id);
            return Json(pro);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }


        [HttpPost]
        public JsonResult Save(string model)
        {
            var projectModel = JsonConvert.DeserializeObject<ProjectModel>(model);
            FetchImage(projectModel);
            var userId = User.Identity.GetUserId();
            var isSave = _services.SaveProject(projectModel, userId);
            return Json(isSave);
        }

        private void FetchImage(ProjectModel projectModel)
        {
            if (Request.Files.Count!=0)
            {
                HttpFileCollectionBase files = Request.Files;
                for (int i = 0; i < files.Count; i++)
                {
                    HttpPostedFileBase file = files[i];
                    var path = Server.MapPath("~/Images/Project/");
                    if (!Directory.Exists(path))
                    {
                        Directory.CreateDirectory(path);
                    }
                    var random = new Random().Next(5555555);
                    var fileName =  random+ "-"+ DateTime.Now.ToString("ddMMyyyhhmmss") + "-"+file.FileName;
                    projectModel.ImageName = fileName;

                    var filePath = Path.Combine(path , fileName);
                    file.SaveAs(filePath);
                }
            }
        }

        //[HttpPost]
        //public JsonResult Save(ProjectModel models)
        //{
        //    var userId = User.Identity.GetUserId();
        //    var isSave = _services.SaveProject(models,userId);
        //    return Json(isSave);
        //}

        [HttpGet]
        public ActionResult Edit(int? id)
        {
            ViewBag.Id = id;
            return View();
        }

        [HttpPost]
        public JsonResult Edit(string model)
        {
            var projectModel = JsonConvert.DeserializeObject<ProjectModel>(model);
            FetchImage(projectModel);
            var userId = User.Identity.GetUserId();
            var isSave = _services.EditProject(projectModel, userId);
            return Json(isSave);
        }

        public ActionResult Detail(string id)
        {
            if (!string.IsNullOrEmpty(id))
            {
                var proId = Convert.ToDecimal(id);
                var model = _services.LoadProjectDetail(proId);
                return View(model);
            }
            else
                return View("Error");
           
        }

    }
}

HPM/Views/Program/Create.cshtml
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section scripts{
    <script src="~/Js/Program/create.js"></script>
}

<div class="row animated fadeIn" ng-controller="createProgramCtrl">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header card-header-primary text-white">
                <strong>Create Program</strong>
            </div>
            <div class="card-block">
                <form name="frm">

                    <div class="row m-1">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label><strong>Name</strong></label>
                                <input type="text" name="name" ng-model="pro.Name" class="form-control" required />
                                <span style="color:red;" ng-if="(frm.name.$touched || frm.name.$dirty ) && frm.name.$invalid">
                                    <span ng-show="frm.name.$error.required">Program name is required. </span>
                                </span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label><strong>Description</strong></label>
                                <textarea class="form-control" ng-model="pro.Description"></textarea>
                            </div>
                        </div>
                    </div>


                    <div class="row m-1">
                        <div class="col-md-12">
                            <button type="button" class="btn btn-sm btn-primary" ng-disabled="frm.$invalid" ng-click="save()"> <span class="fa fa-save"></span> Save</button>
                        </div>
                    </div>
                </form>

            </div>

        </div>
    </div>
</div>

HPM/Views/Program/Edit.cshtml
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section scripts{
    <script src="~/Js/Program/edit.js"></script>
}

<div class="row animated fadeIn" ng-controller="editProgramCtrl">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header card-header-primary text-white">
                <strong>Edit Program</strong>
            </div>
            <div class="card-block">
                <form name="frm">

                    <div class="row m-1">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label><strong>Name</strong></label>
                                <input type="text" name="name" ng-model="pro.Name" class="form-control" required />
                                <span style="color:red;" ng-if="(frm.name.$touched || frm.name.$dirty ) && frm.name.$invalid">
                                    <span ng-show="frm.name.$error.required">Program name is required. </span>
                                </span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label><strong>Description</strong></label>
                                <textarea class="form-control" ng-model="pro.Description"></textarea>
                            </div>
                        </div>

                    </div>


                    <div class="row m-1">
                        <div class="col-md-12">
                            <button type="button" class="btn btn-sm btn-primary" ng-disabled="frm.$invalid" ng-click="save()"> <span class="fa fa-save"></span> Save</button>
                        </div>
                    </div>
                </form>

            </div>

        </div>
    </div>
</div>


<input type="hidden" value="@ViewBag.Id" id="hidId" />

HPM/Views/Program/Index.cshtml
@{
    ViewBag.Title = "Programs";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section scripts{
    <script src="~/Js/Program/index.js"></script>
}

<div class="row animated fadeIn">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header card-header-primary text-white">
                <strong>Programs</strong>
                <a title="Add new Program" class="btn btn-sm btn-outline-primary float-right" style="color:white;" href="@Url.Action("Create","Program")"><span class="fa fa-plus"></span></a>
            </div>
            <div class="card-block">
                <div id="divPartialView">

                </div>
            </div>

        </div>
    </div>
</div>

HPM/Views/Program/Projects.cshtml
@{
    ViewBag.Title = "Projects";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

HPM/Views/Program/_LoadPrograms.cshtml
@model IEnumerable<HPM.Models.ViewModels.ProgramModel>

<table class="table table-hover table-striped table-bordered" id="tbl">
    <thead>
        <tr>
            <th>Sr #</th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>Action</th>
        </tr>

    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td></td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    <a href="@Url.Action("Edit","Program",new { id = item.Id})" target="_blank"><i style="cursor:pointer;" class="fa fa-edit fa-2x"></i> </a>
                    <i style="cursor:pointer;" onclick="disableProgram('@item.Id')" class="fa fa-trash fa-2x"></i>
                </td>
            </tr>
        }
    </tbody>
</table>