HPM/Controllers/ProjectPhasesController.cs
using HPM.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HPM.Models.ViewModels;
using Microsoft.AspNet.Identity;

namespace HPM.Controllers
{
    public class ProjectPhasesController : Controller
    {

        private readonly ProjectIterationService _service;

        public ProjectPhasesController()
        {
            _service = new ProjectIterationService();
        }
        // GET: ProjectPhases
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult LoadProjectsIterations()
        {
            var list = _service.LoadProjectIteration();
            return PartialView("~/Views/ProjectPhases/_LoadProjectsIterations.cshtml", list);
        }

        [HttpPost]
        public ActionResult LoadProjectIterationsDetail(decimal? id)
        {
            var pro = _service.LoadProjectIterationDetail(id);
            return Json(pro);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public JsonResult Save(ProjectIterationModel model)
        {
            var userId = User.Identity.GetUserId();
            var isSave = _service.SaveProjectIteration(model, userId);
            return Json(isSave);
        }

        [HttpGet]
        public ActionResult Edit(int? id)
        {
            ViewBag.Id = id;
            return View();
        }

        [HttpPost]
        public JsonResult Edit(ProjectIterationModel model)
        {
            var userId = User.Identity.GetUserId();
            var isSave = _service.EditProjectIteration(model, userId);
            return Json(isSave);
        }

        public ActionResult Detail(string id)
        {
            if (!string.IsNullOrEmpty(id))
            {
                var proId = Convert.ToDecimal(id);
                var model = _service.LoadProjectIterationDetail(proId);
                return View(model);
            }
            else
                return View("Error");

        }
    }
}

HPM/Views/ProjectPhases/Create.cshtml
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section scripts{
    <!-- AngularJS Material Javascript now available via Google CDN; version 1.1.4 used here -->
    <script src="https://ajax.googleapis.com/ajax/libs/angular_material/1.1.4/angular-material.min.js"></script>
    @*<script src="~/Scripts/Plugins/Angular/ui-bootstrap/ui-bootstrap-tpls-2.5.0.min.js"></script>*@
    <script src="~/Js/ProjectPhase/create.js"></script>
}

<div class="row animated fadeIn" ng-controller="createProjectPhaseCtrl">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header card-header-primary text-white">
                <strong>Create Project Phase</strong>
            </div>
            <div class="card-block">
                <form name="frm">

                    <div class="row m-1">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label><strong>Name</strong></label>
                                <input type="text" name="name" ng-model="proIteration.Name" class="form-control" required />
                                <span style="color:red;" ng-if="(frm.name.$touched || frm.name.$dirty ) && frm.name.$invalid">
                                    <span ng-show="frm.name.$error.required">Phase name is required. </span>
                                </span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label><strong>Project</strong></label>
                                <ui-select ng-model="proIteration.Project" theme="select2" title="Choose a type" name="project" required>
                                    <ui-select-match placeholder="Select a Name">{{$select.selected.Name}}</ui-select-match>
                                    <ui-select-choices repeat="item in Projects | filter:  $select.search">
                                        <div ng-bind-html="item.Name"></div>
                                    </ui-select-choices>
                                </ui-select>
                                <span style="color:red;" ng-show="(frm.project.$touched || frm.project.$dirty) && frm.project.$invalid">
                                    <span ng-show="frm.project.$error.required">Project is required.</span>
                                </span>
                            </div>
                        </div>
                    </div>

                    <div class="row m-1">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label><strong>Start Date</strong></label>
                                <br />
                                <md-datepicker style="float:right" ng-model="proIteration.StartDate" md-placeholder="Enter Start date" name="startDate" required></md-datepicker>
                                <span style="color:red;" ng-if="(frm.startDate.$touched || frm.startDate.$dirty ) && frm.startDate.$invalid">
                                    <span ng-show="frm.startDate.$error.required">Start Date is required. </span>
                                </span>
                            </div>
                        </div>
                        <div class="col-md-6">
                                <div class="form-group">
                                    <label><strong>End Date</strong></label>
                                    <br />
                                    <md-datepicker style="float:right" ng-model="proIteration.EndDate" md-placeholder="Enter End date" name="endDate" md-min-date="proIteration.StartDate" ng-disabled="!proIteration.StartDate" required> </md-datepicker>
                                    @*<p class="input-group">
                                        <input type="text" class="form-control" uib-datepicker-popup="{{format}}" ng-model="proIteration.EndDate" is-open="popup1.opened" datepicker-options="dateOptions" ng-required="false" close-text="Close" alt-input-formats="altInputFormats" name="endDate" />
                                        <span class="input-group-btn">
                                            <button type="button" class="btn btn-default" ng-click="open1()"><i class="fa fa-calendar"></i></button>
                                        </span>
                                    </p>*@
                                    <span style="color:red;" ng-if="(frm.endDate.$touched || frm.endDate.$dirty ) && frm.endDate.$invalid">
                                        <span ng-show="frm.endDate.$error.required">End Date is required. </span>
                                    </span>
                                </div>
                            </div>
                    </div>

                    <div class="row m-1">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label><strong>Description</strong></label>
                                <textarea class="form-control" ng-model="proIteration.Description"></textarea>
                            </div>
                        </div>
                    </div>

                    <div class="row m-1">
                        <div class="col-md-12">
                            <button type="button" class="btn btn-sm btn-primary" ng-disabled="frm.$invalid" ng-click="save()"> <span class="fa fa-save"></span> Save</button>
                        </div>
                    </div>
                </form>

            </div>

        </div>
    </div>
</div>

HPM/Views/ProjectPhases/Edit.cshtml
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section scripts{
    <script src="https://ajax.googleapis.com/ajax/libs/angular_material/1.1.4/angular-material.min.js"></script>
    <script src="~/Js/_ngApp/services/commonService.js"></script> 
    <script src="~/Js/ProjectPhase/edit.js"></script>
}

<div class="row animated fadeIn" ng-controller="editProjectPhaseCtrl">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header card-header-primary text-white">
                <strong>Create Project Phase</strong>
            </div>
            <div class="card-block">
                <form name="frm">

                    <div class="row m-1">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label><strong>Name</strong></label>
                                <input type="text" name="name" ng-model="proIteration.Name" class="form-control" required />
                                <span style="color:red;" ng-if="(frm.name.$touched || frm.name.$dirty ) && frm.name.$invalid">
                                    <span ng-show="frm.name.$error.required">Phase name is required. </span>
                                </span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label><strong>Project</strong></label>
                                <ui-select ng-model="proIteration.Project" theme="select2" title="Choose a type" name="project" required>
                                    <ui-select-match placeholder="Select a Name">{{$select.selected.Name}}</ui-select-match>
                                    <ui-select-choices repeat="item in Projects | filter:  $select.search">
                                        <div ng-bind-html="item.Name"></div>
                                    </ui-select-choices>
                                </ui-select>
                                <span style="color:red;" ng-show="(frm.project.$touched || frm.project.$dirty) && frm.project.$invalid">
                                    <span ng-show="frm.project.$error.required">Project is required.</span>
                                </span>
                            </div>
                        </div>
                    </div>

                    <div class="row m-1">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label><strong>Start Date</strong></label>
                                <md-datepicker style="float:right" ng-model="proIteration.StartDate" md-placeholder="Enter Start date" name="startDate" required></md-datepicker>
                                <span style="color:red;" ng-if="(frm.startDate.$touched || frm.startDate.$dirty ) && frm.startDate.$invalid">
                                    <span ng-show="frm.startDate.$error.required">Start Date is required. </span>
                                </span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label><strong>End Date</strong></label>
                                <md-datepicker style="float:right" ng-model="proIteration.EndDate" md-placeholder="Enter End date" name="endDate" md-min-date="proIteration.StartDate" ng-disabled="!proIteration.StartDate" required></md-datepicker>
                                @*<p class="input-group">
                                        <input type="text" class="form-control" uib-datepicker-popup="{{format}}" ng-model="proIteration.EndDate" is-open="popup1.opened" datepicker-options="dateOptions" ng-required="false" close-text="Close" alt-input-formats="altInputFormats" name="endDate" />
                                        <span class="input-group-btn">
                                            <button type="button" class="btn btn-default" ng-click="open1()"><i class="fa fa-calendar"></i></button>
                                        </span>
                                    </p>*@
                                <span style="color:red;" ng-if="(frm.endDate.$touched || frm.endDate.$dirty ) && frm.endDate.$invalid">
                                    <span ng-show="frm.endDate.$error.required">End Date is required. </span>
                                    <span ng-show="frm.endDate.$error.mindate">Min Date is required. </span>
                                </span>
                            </div>
                        </div>
                    </div>

                    <div class="row m-1">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label><strong>Description</strong></label>
                                <textarea class="form-control" ng-model="proIteration.Description"></textarea>
                            </div>
                        </div>
                    </div>

                    <div class="row m-1">
                        <div class="col-md-12">
                            <button type="button" class="btn btn-sm btn-primary" ng-disabled="frm.$invalid" ng-click="save()"> <span class="fa fa-save"></span> Save</button>
                        </div>
                    </div>
                </form>

            </div>

        </div>
    </div>
</div>

<input type="hidden" value="@ViewBag.Id" id="hidId" />

HPM/Views/ProjectPhases/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section scripts{
    <script src="~/Js/ProjectPhase/index.js"></script>
}

<div class="row animated fadeIn">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header card-header-primary text-white">
                <strong>Project Phases</strong>
                <a title="Add new Project Phases" class="btn btn-sm btn-outline-primary float-right" style="color:white;" href="@Url.Action("Create","ProjectPhases")"><span class="fa fa-plus"></span></a>
            </div>
            <div class="card-block">
                <div id="divPartialView">

                </div>
            </div>

        </div>
    </div>
</div>

HPM/Views/ProjectPhases/_LoadProjectsIterations.cshtml
@model IEnumerable<HPM.Models.ViewModels.ProjectIterationModel>

<table class="table table-bordered table-striped table-hover" id="tbl">
    <thead>
        <tr>
            <th>
                Sr #
            </th>
            <th>
                Project
            </th>
            <th>
                Name
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                Start Date
            </th>
            <th>
                End Date
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td></td>
                <td>
                    @{
                        var project = item.Project?.Name;
                    }
                    @project
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.StartDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EndDate)
                </td>
                <td>
                    <a href="@Url.Action("Edit","ProjectPhases",new { id = item.Id})" target="_blank"><i style="cursor:pointer;" class="fa fa-edit fa-2x"></i> </a>
                </td>
            </tr>
                        }
    </tbody>

</table>